### ISSUE TITLE
4D v16

### ISSUE THREAD

**Issue by olivierfaure** [miyako/4d-plugin-document-properties#1]
All commands are returning an Error -9949 (license or privileges error) in v16beta, is there a solution  ?
Thanks

**Comment by miyako** [comment]
the plugin is not cocoa (as indicated in the readme file, which means its is not 64 bits ready. 
(I guess you are using Mac)

you can try with the 32 bits version of v16 beta to see the difference,
or I can recompile for cocoa if necessary.

**Comment by miyako** [comment]
I've update the plugin to be 64 bits compatible.

**Comment by olivierfaure** [comment]
Hello

Thanks. Due to the error of privileges, i didn't think it could be a 64bits trouble… 

Olivier
